name: ht_email_sendgrid
description: A concrete implementation of the HtEmailClient interface that uses the SendGrid API to send transactional emails.
repository: https://github.com/headlines-toolkit/ht-email-sendgrid
publish_to: none

environment:
  sdk: ^3.8.0

dependencies:
  dio: ^5.8.0+1
  ht_email_client:
    git:
      url: https://github.com/headlines-toolkit/ht-email-client.git
  ht_http_client:
    git:
        url: https://github.com/headlines-toolkit/ht-http-client.git  
  ht_shared:
    git:
      url: https://github.com/headlines-toolkit/ht-shared.git
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
