name: email_sendgrid
description: A concrete implementation of the EmailClient interface that uses the SendGrid API to send transactional emails.
repository: https://github.com/flutter-news-app-full-source-code/email-sendgrid
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: 828b984517edec069266579c624c7af9fbe0e2ac
  dio: ^5.8.0+1
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
      ref: c5e36d06b58918056dde4a58d177a39fb66bfe24
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git  
      ref: 57f6bcfc0f209ecc135fdcb688194045ec87e6e8
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
