name: email_sendgrid
description: A concrete implementation of the EmailClient interface that uses the SendGrid API to send transactional emails.
repository: https://github.com/flutter-news-app-full-source-code/email-sendgrid
publish_to: none

environment:
  sdk: ^3.9.0

dependencies:
  core:
    git:
      url: https://github.com/flutter-news-app-full-source-code/core.git
      ref: v1.2.0
  dio: ^5.8.0+1
  email_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/email-client.git
      ref: v1.0.0
  http_client:
    git:
      url: https://github.com/flutter-news-app-full-source-code/http-client.git  
      ref: v1.0.1
  logging: ^1.3.0

dev_dependencies:
  mocktail: ^1.0.4
  test: ^1.26.2
  very_good_analysis: ^9.0.0
